title: wufangjian
description: My Personal Stack Problems
author: 吴方建
github: https://github.com/wufangjian
about: 前端工程师 / 爱玩儿 / 爱折腾
disqus_shortname: wufangjian
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-skype
      link: "#"
    - icon: fa-twitter
      link: "https://twitter.com/agusmakmun6"
    - icon: fa-linkedin
      link: "#"
    - icon: fa-stack-exchange
      link: "#"

share:
  twitter_username: wufangjian
  fb_appid: 1749788565247320

urls:
    - text: 项目
      url: /projects/
    - text: Github
      url: https://github.com/wufangjian
    - text: 关于我
      url: /about/

url: "https://wufangjian.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist